### ISSUE TITLE
input関数の不具合

### ISSUE THREAD

**Issue by syu-kwsk** [syu-kwsk/python-study#1]
input関数で数値を入力したときは正常に動きます。
```py
hoge = 10

hoge = input()
print(hoge)

#実行結果
10
```
文字を入力すると(上記のコードで　hello　と入力)

```py

#実行結果
Traceback (most recent call last):
  File "main.py", line 8, in <module>
    hoge = input()
  File "<string>", line 1, in <module>
NameError: name 'hello' is not defined
```
なります。NameErrorだったので、入力を文字列みたいにすると
(同じコードで　'hello'　と入力)

```py

#実行結果
hello
```
うまく行きます。
ネットや本のinput()ではクォーテーションを用いなくとも入出力できていましたが、どうしてできないのでしょうか？

またinput()の引数を入力すると

```py
hoge = 10

hoge = input('input:')
print('input is', hoge)

#実行結果

#hello　と入力
input:hello
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    hoge = input('input:')
  File "<string>", line 1, in <module>
NameError: name 'hello' is not defined

# 'hello'　と入力
input:'hello'
('input is', 'hello')

```

となります。
最後の場合(　)や '　' が出力されてしまうのはどうしてでしょうか？
pythonの環境が関係しているような気もしましたがわかりませんでした。

**Comment by tanacchi** [comment]
## 原因

Python2 で走らせているからだと思われます．

Python2 と Python3 では input 関数の挙動に大きな違いがあります．

### input 関数
python2 の input 関数では，入力は式として評価されます．
なので
```python
hoge = input()
```
として，`2 + 5` と入力すると
`hoge` には `7` が入ります．

よって `Hello` と入力すると
`Hello` という変数を参照するので
「`Hello` という変数はありません」っていうエラーが発生します．

### print 関数
python2 では， `print` は, 関数ではなく式です．（if とかも式）
なので，`hoge` の値を print する際は
```python
print hoge
```
とします．

```python
print("input is ", "Hello")
```
と書いた場合，
`"input is"` と`"Hello"` を要素にもつ**タプル**として解釈され
上のように `('input is', 'hello')` 表示されます．

## 解決策

`virtualenv` を作る際に
`python3 -m virtualenv venv` とし，
スクリプトを走らせるときも
`python3 hoge.py`
とすれば直るかと思います．

自分は面倒なので
`alias py='python3'`
として，`py` でpython3 が走るようにしています．

**Comment by syu-kwsk** [comment]
バージョン指定は
` virtualenv my_env --python=/usr/bin/python3.6`で行っていて、　　
コマンドは
`python3 main.c`
でうまくいきました。

参考になります。ありがとうございました。
